Feature/external dummy herds
NBISweden/theherdbook pull request #151
Opened 2020-10-21 09:59 UTC by kusalananda

Adding dummy herds `GX1` and `MX1` for the two genebanks.  These will hold the animals sold outside of the genebanks (by means of entries added to the `gene_tracking` table).

2020-10-21 10:15 UTC, norling requested changes
If we're going to allow multiple letters in Herd prefixes you need to update the regexps in `frontend/src/user_context.tsx: canEdit()` so that they still trigger. This probably won't be an issue for the dummy herds, but if we allow these herds then the code should reflect that.

2020-10-21 15:37 UTC, kusalananda commented
> If we're going to allow multiple letters in Herd prefixes you need to update the regexps in `frontend/src/user_context.tsx: canEdit()` so that they still trigger. This probably won't be an issue for the dummy herds, but if we allow these herds then the code should reflect that.

This is addressed in commit  7f164a4.

2020-10-21 15:40 UTC, kusalananda commented
Dummy herds now added, but data for dummy herds is only available for Gotlandskanin as Mellerudskanin does not annotate animals sold to herds outside of the genebank.

2020-10-21 18:02 UTC, jhagberg approved these changes
LGTM good with name "Externa djur"

2020-10-22 06:45 UTC, norling approved these changes

2020-10-22 07:34 UTC, merged