Handling of external authentication
NBISweden/theherdbook pull request #192
Opened 2020-12-11 11:04 UTC by pontus

2020-12-11 12:41 UTC, danr commented
I think there must be some better way than a timeout at `waitForExternalLogin`. Waiting seems like some kind of way of polling. 

In `waitForExternalLogin` you extract the returned user by trimming the text in the body. There surely must be some way to return a json object instead.

I don't understand how the rest of the page figures out if it is logged in or not.

I don't understand this comment:  `// We are not doing account linking`.

2020-12-11 13:02 UTC, pontus commented
> I think there must be some better way than a timeout at `waitForExternalLogin`. Waiting seems like some kind of way of polling.

It is polling, in a sense. I'd be happy for alternative suggestions. The one I can think of involves doing it in the same window add doing a redirect in the end.
 
> In `waitForExternalLogin` you extract the returned user by trimming the text in the body. There surely must be some way to return a json object instead.

Sure. Responses from the python are subject to change still (so far mimics what was there before).

> I don't understand how the rest of the page figures out if it is logged in or not.

As ar as I understand, this is handled by the bits looking user (in useEffect and close to that).

> I don't understand this comment: `// We are not doing account linking`.

To make things less confusing on the server part (and what needs to be done at the external service), the server shares some things between linking and login. For this, we do an extra call to signal that we're not doing linking. (It's possible that can be improved somehow on the server side).

2020-12-11 13:25 UTC, danr commented
> As ar as I understand, this is handled by the bits looking at user (in useEffect and close to that).

I mean how (and where) is this user populated from information from the external login services?

2020-12-11 13:42 UTC, pontus commented
(I

> > As ar as I understand, this is handled by the bits looking at user (in useEffect and close to that).
> 
> I mean how (and where) is this user populated from information from the external login services?

Ah, that can probably be improved. For now it does a full reload and lets the rest of the app figure out it's logged in (which it seems to do by asking the server - `on_mount` in `user_context.tsx`).

[I'm somewhat torn about where the code is best placed.]

2020-12-11 13:47 UTC, danr commented
I think full reload is totally OK for external login. Can this be used to avoid doing the `window.open` and the polling?

2020-12-11 13:53 UTC, pontus commented
> I think full reload is totally OK for external login. Can this be used to avoid doing the `window.open` and the polling?

Nah, those are separate. It would rather be adding an optional parameter to the route(s) in react and having the server doing redirect to that address at the end (that would be kind of bad because it means we introduce requirements for the client to behave in certain ways).

2021-04-19 12:54 UTC, jhagberg commented
the organization now have a Google workspace would it possbile to only allow users using  a google acount from that workspace?

2021-04-20 11:56 UTC, pontus commented
Yes, and indeed without it ever being visible to the herdbook - when setting up the requisites for oauth2 with an organization, one can choose to have the application internal only, meaning it will return a failure if authentication is done with an account from another domain.

2021-06-01 12:37 UTC, jonandernovella commented on app/utils/database.py
> +    Migrate between schema version 4 and 5.
This will likely be a conflict.

2021-06-08 09:02 UTC, jonandernovella requested changes

2021-06-08 09:02 UTC, jonandernovella commented on app/herdbook.py
> +    Do an external authentication. The special sercvice
```suggestion
    Do an external authentication. The special service
```

2021-06-08 09:03 UTC, jonandernovella commented
Would be nice to keep the user's full name in our database

2021-06-08 09:26 UTC, jonandernovella commented on app/utils/external_auth.py
> +    return None
I think that here we could send the full name

2021-06-09 10:57 UTC, pontus commented on app/herdbook.py
> +    Do an external authentication. The special sercvice
Fixed.

2021-06-09 10:58 UTC, pontus commented on app/utils/database.py
> +    Migrate between schema version 4 and 5.
Correct, it was, should be fixed now.

2021-06-09 11:37 UTC, jonandernovella commented on app/utils/data_access.py
> +                .get()
This could be a separate function. But I think it's fine.

2021-06-09 11:39 UTC, jonandernovella approved these changes
LGTM!

2021-06-09 11:40 UTC, merged