Add cache as suggested and start job refreshing cache at startup
NBISweden/theherdbook pull request #266
Opened 2021-05-06 12:20 UTC by pontus

2021-05-07 09:28 UTC, inghylt approved these changes
Nice!

2021-05-10 08:19 UTC, jhagberg requested changes

2021-05-10 08:19 UTC, jhagberg commented on app/herdbook.py
> +KINSHIP_LIFETIME = 300
This could probably be longer. Very long if we can force to update the cache when adding new animals?

2021-05-10 08:19 UTC, jhagberg commented on app/herdbook.py
> +@CACHE.cached(timeout=KINSHIP_LIFETIME, key_prefix="R-api")
the CACHE should be on the internal  get_kinship(p.id)

2021-05-10 08:19 UTC, jhagberg commented on app/herdbook.py
> +KINSHIP_LIFETIME = 300
Alright, so you are updating the kinshipmatrix every 15 s that will work but will reload with the same data many times. could we instead force a cache to reload when new animals get registered? But this could probably work but if we check every 30 min and cache is 1 hour long or something. They usually update this matrix once per year.

2021-05-10 08:54 UTC, pontus commented on app/herdbook.py
> +KINSHIP_LIFETIME = 300
No, from what I understand (and my interpretations of what I've seen), data is not reloaded every time, instead the incurred cost is the cost of getting the cached data every 15 seconds.

The first calls before the `r-api` is up and answering will fail, so having a low value is a "practical" work around to trying to sync that.

We can certainly increase the cache lifetime and add invalidation on updates.

2021-05-10 08:55 UTC, pontus commented on app/herdbook.py
> +@CACHE.cached(timeout=KINSHIP_LIFETIME, key_prefix="R-api")
Ah, I must have messed things up when pushing vs testing, true and would give pessimal behaviour.

2021-05-10 14:27 UTC, pontus commented on app/herdbook.py
> +@CACHE.cached(timeout=KINSHIP_LIFETIME, key_prefix="R-api")
Fixed.

2021-05-11 08:18 UTC, jhagberg commented on app/herdbook.py
> +KINSHIP_LIFETIME = 300
Okey so its realoded ever 300 s ?

2021-05-11 09:38 UTC, jhagberg approved these changes

2021-05-11 09:38 UTC, jhagberg commented
Lets merge this for now

2021-05-11 09:39 UTC, merged