Replace herd form with heading
NBISweden/theherdbook pull request #369
Opened 2021-08-19 08:42 UTC by jonandernovella

Fixes #368

2021-08-19 13:12 UTC, HenrikeW commented
By doing this, we remove the option for a herd owner (that is not admin or manager) to edit information about his/her herd. Until now, there has been an [Edit] link that would open the herd form. 
I always thought it was a weird place for it, but removing it entirely is not an option either, even if it might fix the duplicate fetching. 
So before doing this, we would need to implement the herd form for owners at some other place in the page, I think. 
One option could be to extend the "Inställningar" tab to become something like "My profile" where you can change your password and edit information you want to provide about your herd?

2021-08-19 13:13 UTC, HenrikeW requested changes
By doing this, we remove the option for a herd owner (that is not admin or manager) to edit information about his/her herd. Until now, there has been an [Edit] link that would open the herd form.
I always thought it was a weird place for it, but removing it entirely is not an option either, even if it might fix the duplicate fetching.
So before doing this, we would need to implement the herd form for owners at some other place in the page, I think.
One option could be to extend the "Inställningar" tab to become something like "My profile" where you can change your password and edit information you want to provide about your herd?

2021-08-19 15:38 UTC, airenzp commented
I agree with Henrike. This removes the edit herd function, not quite visible here. It sounds like a good idea actually to move it to the place Henrike suggest. I think Jon is trying to avoid the delay when loading a herd by removing this function, but I still see the delay when testing in my environment for the GX1. And I see the same write error we talked about. The pedigree is also heavy to read.

2021-08-19 15:42 UTC, airenzp commented
Is this PR related with the dev/efficiency one? Maybe there we keep this function?

2021-08-20 08:38 UTC, HenrikeW approved these changes
Looks good now I think, nice work. 
It feels like herds load a little bit quicker than before, but I don't have numbers on that. 
GX1 is still incredibly slow, 1:21min it took for me. But I guess that's expected.

2021-08-20 08:38 UTC, HenrikeW commented on frontend/src/herdForm.tsx
> +    else {
Great! Good solution, I think :+1:

2021-08-20 08:52 UTC, merged