Update issue templates
NBISweden/theherdbook pull request #469
Opened 2021-11-09 13:54 UTC by jhagberg

Issue templates for bugs

2021-11-10 12:33 UTC, HenrikeW approved these changes
Looks good but I think it would be interesting to hear feedback from the test users on this, to see if it's understandable for non-tech-savvy people who are not used to report bugs. Some thoughts:
- Should we give them a hint how to find out what version their browser is? I just googled "What version is my firefox" to find out, but I'm not sure if everyone would do that. We could either tell them to google or describe where to find the information in the most common browsers. (In firefox and chrome it's in Help --> About <browser name>
- "Ytterligare sammanhang" sounds a bit weird to me. Is that auto-translated? Or is it just me, non-native Swedish speaker? I would rather phrase it "Ytterligare information". "Lägg till annan information, som du tror kan vara relevant för problemet, här", or something like that. 

I still approve, as these might be non-issues.

2021-11-10 12:36 UTC, jhagberg commented
Yes it's just a first auto-translation you suggestions is much better I add that. We can also wait a bit with this merge

2021-11-17 13:11 UTC, kusalananda requested changes
Initial review of actual text. The text requires changes. I have not thought about whether something is missing but will go through it again soon.

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +**Smartphone (fyll i följande information):**
```suggestion
**Mobil enhet (fyll i följande information):**
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +- Enhet: [t.ex. iPhone 6]
```suggestion
- Modell: [t.ex. iPhone 6]
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +**Skrivbord (vänligen fyll i följande information):**
```suggestion
**Dator (vänligen fyll i följande information):**
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +2. Klicka på '...'
Inconsistent quotes.

```suggestion
2. Klicka på "..."
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/bug-report-en.md
> +**Smartphone (please complete the following information):**
"Smartphone" is very American and not quite what we want to know.  We want to distinguish a desktop/laptop from a mobile device with a much smaller screen (mobile phone or tablet).

```suggestion
**Mobile device (please complete the following information):**
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +Lägg till någon annan inoformation om problemet här.
```suggestion
Lägg till någon annan information om problemet här.
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/bug-report-en.md
> +title: ''
Consistent quoting and use of ellipses.

```suggestion
title: "..."
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/bug-report-en.md
> +3. Scroll down to '....'
```suggestion
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +title: ''
```suggestion
title: "..."
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +- Version [t.ex. 22]  [Tryck här för instruktioner](https://www.computerhope.com/issues/ch001329.htm)
```suggestion
- Webbläsare: [t.ex. Chrome, Firefox, Safari]
- Version: [t.ex. 22]  [Länk till instruktioner](https://www.computerhope.com/issues/ch001329.htm)
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/rapportera-fel-p--svenska.md
> +- Version [t.ex. 22]
"Aktiewebbläsare"!

```suggestion
- Webbläsare: [t.ex. Chrome, Firefox, Safari]
- Version: [t.ex. 22]
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/bug-report-en.md
> +- Version [e.g. 22]
Several of these suggestions here and further down:
1. Missing `:`.
2. Use the same list of main browsers.

```suggestion
- Browser: [e.g. Chrome, Firefox, Safari]
- Version: [e.g. 22]
```

2021-11-17 13:11 UTC, andkaha commented on .github/ISSUE_TEMPLATE/bug-report-en.md
> +- Version [e.g. 22] [Link to instuctions](https://www.computerhope.com/issues/ch001329.htm)
```suggestion
- Browser: [e.g. Chrome, Firefox Safari]
- Version: [e.g. 22] [Link to instuctions](https://www.computerhope.com/issues/ch001329.htm)
```

2021-11-17 13:17 UTC, jhagberg commented
Fixed suggestions changed a typo

2021-11-17 13:28 UTC, kusalananda approved these changes
Looks ok.

2021-11-17 13:28 UTC, merged