Add module for computing indreeding coefficients
NBISweden/theherdbook pull request #72
Opened 2020-06-02 15:51 UTC by jonandernovella

A PoC module has been added in order to compute inbreeding coefficients using pydigree.

2020-06-02 16:17 UTC, danr commented on app/utils/inbreeding.py
> +        self.fam = individual["nerd_id"]
herd id?

2020-06-02 16:19 UTC, danr commented on app/utils/inbreeding.py
> +        self.fam = individual["nerd_id"]
:nerd_face:

2020-06-04 10:31 UTC, norling requested changes
Looks good in general, but there are some minor things:

1. `/api/coefficients` is not a great name for the endpoint. Maybe something like `/api/inbreeding`?
2. There are some pylint complaints, and it's always nice to keep pylint happy! :) 
3. Could you add some tests just to make sure that things only crash and burn when appropriate? 
4. There should probably be some access control on this endpoint, so just check the target individuals genebank against the `user.accessible_genebanks` (once #71 is merged)

2020-06-05 12:40 UTC, norling approved these changes

2020-06-05 12:40 UTC, merged