Feature/inbreeding
NBISweden/theherdbook pull request #91
Opened 2020-07-21 11:27 UTC by airenzp

This branch adds mainly the inbreeding coefficient to the interface, with cache management. It also includes a bugfix to avoid errors when one of the parents is missing, but not both. 
The documentation for the dev setup is also updated with the steps required to run a local environment and create an admin user.

2020-08-18 11:30 UTC, jonandernovella approved these changes

2020-08-18 11:41 UTC, danr reviewed
One typo

app/herdbook.py has some formatting oddities... run black?

2020-08-18 11:41 UTC, danr commented on frontend/individual.tsx
> +            <dt>Navelskoefficient</dt> <dd>{individual.inbreeding}%</dd>
Isn't it _Inavelskoefficent_?

2020-08-18 11:43 UTC, jhagberg commented on frontend/individual.tsx
> +            <dt>Navelskoefficient</dt> <dd>{individual.inbreeding}%</dd>
yes

2020-08-18 11:49 UTC, airenzp commented on frontend/individual.tsx
> +            <dt>Navelskoefficient</dt> <dd>{individual.inbreeding}%</dd>
tack! I edited the file

2020-08-18 11:54 UTC, danr approved these changes

2020-08-18 11:59 UTC, pontus requested changes

2020-08-18 11:59 UTC, pontus commented on docker-compose.yml
> +            - 5432:5432
Why do we want to expose the database?

2020-08-18 11:59 UTC, pontus commented on README.md
> +python3 -c "from utils.data_access import register_user; register_user('user@domain.com', 'userpassword', privileges=[{'level': 'admin'}])
Better to refer to `register_user.sh` here (and adding privileges there).

2020-08-18 13:25 UTC, norling approved these changes

2020-08-18 13:54 UTC, airenzp commented on docker-compose.yml
> +            - 5432:5432
ok, I remove it. Was using it in my local env

2020-08-18 13:55 UTC, airenzp commented on README.md
> +python3 -c "from utils.data_access import register_user; register_user('user@domain.com', 'userpassword', privileges=[{'level': 'admin'}])
register user was trying to run on localhost, and failing, in this way I could solve it

2020-08-18 15:56 UTC, airenzp commented on README.md
> +python3 -c "from utils.data_access import register_user; register_user('user@domain.com', 'userpassword', privileges=[{'level': 'admin'}])
I tried the script again and it is working. Maybe the merge solved the connection issues. Anyway, I refer now to the script and add the admin rights there.

2020-08-19 08:17 UTC, danr commented
What about running black with `--skip-string-normalization`? That way it won't touch all the single quotes.

2020-08-19 08:21 UTC, pontus approved these changes

2020-08-21 07:41 UTC, merged